"""Thin mission layer around the existing CoreAgentLoop."""

from affordance_runtime.mission.boundary import AuditBoundary
from affordance_runtime.mission.contracts import (
    AcceptedFact,
    AcceptedWorkingOutcome,
    AuditGuidance,
    AuditorDecision,
    AuditorPort,
    AuditorRoleRequest,
    AuditorTaskProjection,
    EpisodeMonitorEvent,
    EpisodeMonitorRecommendation,
    EpisodeMonitorTransition,
    EvidenceBoundaryResult,
    EvidenceBundle,
    ExecutionMode,
    ManagerAssessment,
    ManagerDecision,
    ManagerPort,
    ManagerRecoveryView,
    ManagerRequestMode,
    ManagerRoleRequest,
    ManagerRoute,
    MissionEnvironmentView,
    MissionOutcome,
    MissionState,
    RecoveryKind,
    RecoverySignal,
    SubtaskContract,
    SupervisorPhase,
    SupervisorState,
    WorkingFactProposal,
    WorkingOutcomeProposal,
    WorkingStateProposal,
)
from affordance_runtime.mission.finalization import (
    FinalResponseBoundary,
    FinalResponseBoundaryResult,
    FinalResponseRejection,
)
from affordance_runtime.mission.goal_projection import subtask_goal_resolution
from affordance_runtime.mission.monitor import EpisodeMonitor, EpisodeMonitorConfig
from affordance_runtime.mission.supervisor import MissionRunResult, MissionSupervisor

__all__ = [
    "AcceptedFact",
    "AuditGuidance",
    "AuditBoundary",
    "EvidenceBoundaryResult",
    "EvidenceBundle",
    "AuditorDecision",
    "ManagerAssessment",
    "ManagerRequestMode",
    "WorkingStateProposal",
    "AcceptedWorkingOutcome",
    "AuditorPort",
    "AuditorRoleRequest",
    "AuditorTaskProjection",
    "EpisodeMonitor",
    "EpisodeMonitorConfig",
    "EpisodeMonitorEvent",
    "EpisodeMonitorRecommendation",
    "EpisodeMonitorTransition",
    "ExecutionMode",
    "FinalResponseBoundary",
    "FinalResponseBoundaryResult",
    "FinalResponseRejection",
    "RecoveryKind",
    "RecoverySignal",
    "ManagerDecision",
    "MissionEnvironmentView",
    "ManagerPort",
    "ManagerRecoveryView",
    "ManagerRoleRequest",
    "ManagerRoute",
    "MissionOutcome",
    "MissionState",
    "MissionRunResult",
    "MissionSupervisor",
    "WorkingOutcomeProposal",
    "WorkingFactProposal",
    "SubtaskContract",
    "SupervisorPhase",
    "SupervisorState",
    "subtask_goal_resolution",
]
