"""Thin milestone mission layer around the existing CoreAgentLoop."""

from affordance_runtime.mission.boundary import EvidenceBoundary
from affordance_runtime.mission.contracts import (
    AcceptedFact,
    AcceptedWorkingOutcome,
    AuditorDecision,
    AuditorPort,
    AuditorRoleRequest,
    AuditorTaskProjection,
    EpisodeMonitorEvent,
    EpisodeMonitorRecommendation,
    EpisodeMonitorTransition,
    EvidenceAssessment,
    EvidenceBoundaryRejectionClass,
    EvidenceBoundaryResult,
    EvidenceBundle,
    EvidenceRequirement,
    ExecutionMode,
    Milestone,
    MilestoneAdmission,
    MilestoneAdmissionRoute,
    MilestoneRoadmap,
    MissionEnvironmentView,
    MissionOutcome,
    MissionState,
    PlannerDecision,
    PlannerPort,
    PlannerRecoveryView,
    PlannerRequestMode,
    PlannerRoleRequest,
    PlannerRoute,
    PublicOutcomeSummary,
    RecoveryKind,
    RecoverySignal,
    SupervisorPhase,
    SupervisorState,
    WorkingFactProposal,
    WorkingOutcomeProposal,
    WorkingStateProposal,
)
from affordance_runtime.mission.finalization import (
    FinalResponseBoundary,
    FinalResponseBoundaryResult,
    FinalResponseRejection,
)
from affordance_runtime.mission.goal_projection import milestone_goal_resolution
from affordance_runtime.mission.monitor import EpisodeMonitor, EpisodeMonitorConfig
from affordance_runtime.mission.supervisor import MissionRunResult, MissionSupervisor

__all__ = [
    "AcceptedFact",
    "AcceptedWorkingOutcome",
    "AuditorDecision",
    "AuditorPort",
    "AuditorRoleRequest",
    "AuditorTaskProjection",
    "EpisodeMonitor",
    "EpisodeMonitorConfig",
    "EpisodeMonitorEvent",
    "EpisodeMonitorRecommendation",
    "EpisodeMonitorTransition",
    "EvidenceAssessment",
    "EvidenceBoundary",
    "EvidenceBoundaryRejectionClass",
    "EvidenceBoundaryResult",
    "EvidenceBundle",
    "EvidenceRequirement",
    "ExecutionMode",
    "FinalResponseBoundary",
    "FinalResponseBoundaryResult",
    "FinalResponseRejection",
    "Milestone",
    "MilestoneAdmission",
    "MilestoneAdmissionRoute",
    "MilestoneRoadmap",
    "MissionEnvironmentView",
    "MissionOutcome",
    "MissionRunResult",
    "MissionState",
    "MissionSupervisor",
    "PlannerDecision",
    "PlannerPort",
    "PlannerRecoveryView",
    "PlannerRequestMode",
    "PlannerRoleRequest",
    "PlannerRoute",
    "PublicOutcomeSummary",
    "RecoveryKind",
    "RecoverySignal",
    "SupervisorPhase",
    "SupervisorState",
    "WorkingFactProposal",
    "WorkingOutcomeProposal",
    "WorkingStateProposal",
    "milestone_goal_resolution",
]
