"""Product façade, composition, and command entrypoint."""

from affordance_runtime.app.checkpoint import (
    RUNTIME_CHECKPOINT_SCHEMA_VERSION,
    RuntimeCheckpoint,
    RuntimeCheckpointCommandOutcome,
    RuntimeCheckpointError,
    RuntimeCheckpointResumeOutcome,
    RuntimeCheckpointRevisionOutcome,
    RuntimeCheckpointStore,
    SQLiteRuntimeCheckpointStore,
)
from affordance_runtime.app.composition import (
    compose_target_runtime,
    compose_target_runtime_from_environment,
)
from affordance_runtime.app.public_session import (
    PUBLIC_SESSION_SCHEMA_VERSION,
    PublicRuntimeSessionEvent,
    PublicRuntimeSessionFactory,
    PublicRuntimeSessionHandle,
    PublicRuntimeSessionSnapshot,
    PublicSessionCapability,
    PublicSessionConflict,
    PublicSessionOpenError,
    PublicSessionOpenStage,
    PublicSessionStatus,
    PublicTaskRequestFactory,
    RuntimeEnvironmentLease,
    TargetRuntimeFactory,
    TargetRuntimeSession,
    TargetRuntimeSessionFactory,
    default_public_task_request,
)
from affordance_runtime.app.runtime import (
    TargetRuntime,
    TargetRuntimeRevisionOutcome,
    TargetRuntimeRunOutcome,
)

__all__ = [
    "TargetRuntime",
    "TargetRuntimeRunOutcome",
    "TargetRuntimeRevisionOutcome",
    "RUNTIME_CHECKPOINT_SCHEMA_VERSION",
    "RuntimeCheckpoint",
    "RuntimeCheckpointCommandOutcome",
    "RuntimeCheckpointError",
    "RuntimeCheckpointRevisionOutcome",
    "RuntimeCheckpointResumeOutcome",
    "RuntimeCheckpointStore",
    "SQLiteRuntimeCheckpointStore",
    "PUBLIC_SESSION_SCHEMA_VERSION",
    "PublicRuntimeSessionFactory",
    "PublicRuntimeSessionEvent",
    "PublicRuntimeSessionHandle",
    "PublicRuntimeSessionSnapshot",
    "PublicSessionCapability",
    "PublicSessionConflict",
    "PublicSessionOpenError",
    "PublicSessionOpenStage",
    "PublicSessionStatus",
    "PublicTaskRequestFactory",
    "RuntimeEnvironmentLease",
    "TargetRuntimeFactory",
    "TargetRuntimeSession",
    "TargetRuntimeSessionFactory",
    "default_public_task_request",
    "compose_target_runtime",
    "compose_target_runtime_from_environment",
]
