"""Unified world contracts and runtime-owned action-space services."""

from affordance_runtime.world.acquisition import (
    AcquisitionOrigin,
    AcquisitionStatus,
    ExecutionOutcome,
    ObservationAcquisition,
    ObservationCapabilities,
    ObservationOffer,
    ObservationRequestKind,
    ObservationSelectionPlan,
    SourceAcquisitionResult,
    SourceAcquisitionStatus,
    SourceRequirement,
    SourceSelection,
    WorldObservationRequest,
)
from affordance_runtime.world.action_paging import ActionPager, InternalActionPage
from affordance_runtime.world.action_space import ActionAdmissionResult, ActionSpaceBuilder
from affordance_runtime.world.admission_issue import AdmissionIssue, AdmissionIssueCode
from affordance_runtime.world.binder import ActionBinder, BindingError
from affordance_runtime.world.contracts import (
    ActionBinding,
    ActionOption,
    ActionRisk,
    ActionSpace,
    AdmittedActionSelection,
    CoverageState,
    EntityCorrespondence,
    EntityInventoryIssueCode,
    EntityInventoryStatus,
    EntityInventorySummary,
    ObservationConflict,
    ObservationGroundingRegion,
    ObservationMedia,
    ObservationStructureNode,
    SemanticTarget,
    StateFact,
    SurfaceObservation,
    WorldObservation,
)
from affordance_runtime.world.fusion import (
    FusedEntityProvenance,
    FusionStatus,
    WorldFusion,
    WorldFusionResult,
)
from affordance_runtime.world.interaction_capabilities import (
    INTERACTION_CAPABILITY_REGISTRY,
    AdapterCapabilitySupport,
    AdapterInteractionProfile,
    CapabilityComposer,
    ComposedAdapterCapability,
    ComposedInteractionCapabilities,
    DestinationMode,
    InteractionCapabilityError,
    InteractionCapabilityIssueCode,
    InteractionCapabilityRegistry,
    InteractionSubjectKind,
    ParameterContractKind,
    PrimitiveTranslator,
    SemanticActionDefinition,
    VerificationContract,
    VerificationFamily,
    verification_contract_for_action,
)
from affordance_runtime.world.observation_orchestrator import (
    ObservationOrchestrator,
    ObservationSelectionResult,
)
from affordance_runtime.world.relevance import (
    ActionRelevance,
    ActionRelevancePolicy,
    ActionRelevanceRole,
)
from affordance_runtime.world.route_selector import (
    RouteSelectionCode,
    RouteSelectionResult,
    RouteSelector,
)
from affordance_runtime.world.semantic_inventory import (
    MAX_SEMANTIC_INVENTORY_COUNT,
    SemanticInventoryStatus,
    SemanticInventorySummary,
)
from affordance_runtime.world.source_profile import (
    AcquisitionCost,
    ObservationAssurance,
    ObservationModality,
    ObservationSourceProfile,
    VerificationStrength,
    assurance_satisfies,
)
from affordance_runtime.world.view import AgentTargetView, AgentWorldView, build_agent_world_view
from affordance_runtime.world.vision_escalation import (
    VisionEscalationDecision,
    VisionEscalationMode,
    VisionEvidenceNeed,
    decide_visual_escalation,
    derive_visual_evidence_needs,
)

__all__ = [
    "ActionBinder",
    "AcquisitionOrigin",
    "AcquisitionStatus",
    "ActionPager",
    "ActionRelevance",
    "ActionRelevancePolicy",
    "ActionRelevanceRole",
    "ActionBinding",
    "ActionOption",
    "ActionRisk",
    "ActionSpace",
    "ActionSpaceBuilder",
    "ActionAdmissionResult",
    "AdmissionIssue",
    "AdmissionIssueCode",
    "AdmittedActionSelection",
    "AcquisitionCost",
    "AgentTargetView",
    "AgentWorldView",
    "BindingError",
    "CoverageState",
    "EntityInventoryIssueCode",
    "EntityInventoryStatus",
    "EntityInventorySummary",
    "EntityCorrespondence",
    "ExecutionOutcome",
    "InternalActionPage",
    "ObservationAssurance",
    "ObservationAcquisition",
    "ObservationCapabilities",
    "ObservationConflict",
    "ObservationGroundingRegion",
    "ObservationMedia",
    "ObservationStructureNode",
    "ObservationModality",
    "ObservationOffer",
    "ObservationSelectionPlan",
    "ObservationOrchestrator",
    "ObservationSelectionResult",
    "ObservationRequestKind",
    "ObservationSourceProfile",
    "SourceAcquisitionResult",
    "SourceAcquisitionStatus",
    "SourceRequirement",
    "SourceSelection",
    "FusedEntityProvenance",
    "FusionStatus",
    "WorldFusion",
    "WorldFusionResult",
    "INTERACTION_CAPABILITY_REGISTRY",
    "AdapterCapabilitySupport",
    "AdapterInteractionProfile",
    "CapabilityComposer",
    "ComposedAdapterCapability",
    "ComposedInteractionCapabilities",
    "DestinationMode",
    "InteractionCapabilityError",
    "InteractionCapabilityIssueCode",
    "InteractionCapabilityRegistry",
    "InteractionSubjectKind",
    "ParameterContractKind",
    "PrimitiveTranslator",
    "SemanticActionDefinition",
    "VerificationContract",
    "VerificationFamily",
    "RouteSelectionCode",
    "RouteSelectionResult",
    "RouteSelector",
    "SemanticTarget",
    "SemanticInventoryStatus",
    "SemanticInventorySummary",
    "MAX_SEMANTIC_INVENTORY_COUNT",
    "StateFact",
    "SurfaceObservation",
    "WorldObservation",
    "WorldObservationRequest",
    "VisionEscalationDecision",
    "VisionEvidenceNeed",
    "VisionEscalationMode",
    "decide_visual_escalation",
    "derive_visual_evidence_needs",
    "VerificationStrength",
    "build_agent_world_view",
    "assurance_satisfies",
    "verification_contract_for_action",
]
