"""Target execution contracts, including bounded current-form execution receipts."""

from affordance_runtime.execution.contracts import (
    ActionDispatchCancelled,
    ActionError,
    ActionIntent,
    ActionResult,
    BoundActionRequest,
    BoundFormFieldsRequest,
    DispatchStatus,
    ExecutionAttempt,
    ExecutionCancellationPhase,
    ExecutionCancelled,
    ExecutionCompletion,
    ExecutionDiagnostic,
    ExecutionDiagnosticPhase,
    ExecutionObservationRecovery,
    ExecutionOutcome,
    ExecutionReceipt,
    ExecutionReceiptBatch,
    FormFieldsExecutionCancelled,
    FormFieldsExecutionOutcome,
    SessionHealth,
    SessionHealthStatus,
)
from affordance_runtime.execution.diagnostics import execution_diagnostic_from_exception

__all__ = [
    "ActionDispatchCancelled",
    "ActionError",
    "ActionIntent",
    "ActionResult",
    "BoundActionRequest",
    "BoundFormFieldsRequest",
    "DispatchStatus",
    "ExecutionAttempt",
    "ExecutionCancelled",
    "ExecutionCancellationPhase",
    "ExecutionCompletion",
    "ExecutionDiagnostic",
    "ExecutionDiagnosticPhase",
    "ExecutionOutcome",
    "ExecutionObservationRecovery",
    "ExecutionReceipt",
    "ExecutionReceiptBatch",
    "FormFieldsExecutionOutcome",
    "FormFieldsExecutionCancelled",
    "SessionHealth",
    "SessionHealthStatus",
    "execution_diagnostic_from_exception",
]
